name: vention_rail_module
services:
  vention_rail_module:
    container_name: vention_rail_module
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${IMAGE}:latest
        - ${IMAGE}:dev
    command: python -m ur_rest_node --port 3011 --ur_ip ${UR_IP}
    env_file: .env
    volumes:
      - ./src:/home/app/vention_rail_module/src
      - ./tests:/home/app/vention_rail_module/tests
    ports:
      - 3011:3011
