name: vention_rail_module
services:
  vention_rail_module:
    container_name: vention_rail_module
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${IMAGE}:latest
        - ${IMAGE}:dev
    command: python -m rail_rest_node --rail_ip ${RAIL_IP}
    env_file: .env
    volumes:
      - ./src:/home/app/vention_rail_module/src
      - ./tests:/home/app/vention_rail_module/tests
    ports:
      - 3022:3022
