name: vention_rail_module
services:
  vention_rail_module:
    container_name: vention_rail_module
    image: ghcr.io/ad-sdl/vention_rail_module
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/ad-sdl/vention_rail_module:latest
        - ghcr.io/ad-sdl/vention_rail_module:dev
    command: python -m rail_rest_node
    env_file: .env
    volumes:
      - ./src:/home/app/vention_rail_module/src
      - ./tests:/home/app/vention_rail_module/tests
    ports:
      - 3022:3022
